# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-18 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=32)),
                ('transaction_type', models.CharField(choices=[('COLLECTION', 'COLLECTION'), ('AIRTIME', 'AIRTIME'), ('PAYOUT', 'PAYOUT')], max_length=64)),
                ('entry_type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=15)),
                ('category', models.CharField(choices=[('REGISTRATION', 'REGISTRATION')], max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED'), ('INDETERMINATE', 'INDETERMINATE'), ('CANCELED', 'CANCELED')], max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('request', models.TextField()),
                ('request_date', models.DateField()),
                ('response', models.TextField(blank=True, null=True)),
                ('response_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_transaction',
            },
        ),
    ]
