# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpayment',
            name='transaction_id',
            field=models.CharField(default=b'', max_length=255),
            preserve_default=False,
        ),
    ]
