# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_memberpayment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK'), ('MOBILE MONEY', 'MOBILE MONEY')], default=b'', max_length=10),
            preserve_default=False,
        ),
    ]
