# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_cooperativemember_county'),
        ('payment', '0003_memberpayment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=255)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=32)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.CooperativeMember')),
            ],
            options={
                'db_table': 'member_payment_transaction',
            },
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='payemnt_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberpaymenttransaction',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.MemberPayment'),
        ),
    ]
