# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 03:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coop', '0004_cooperativemember_county'),
        ('payment', '0004_auto_20190305_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('status', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], max_length=10)),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_payment_request',
            },
        ),
        migrations.CreateModel(
            name='BulkPaymentRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('payment_method', models.CharField(max_length=10)),
                ('transaction_date', models.DateField()),
                ('process_state', models.BooleanField(default=0)),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('bulk_payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.BulkPaymentRequest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.CooperativeMember')),
            ],
            options={
                'db_table': 'bulk_payment_request_log',
            },
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], max_length=15),
        ),
    ]
