# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190306_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpaymentrequest',
            name='payment_method',
            field=models.CharField(default=b'', max_length=10),
            preserve_default=False,
        ),
    ]
