# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_cooperativemember_county'),
        ('payment', '0006_bulkpaymentrequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpaymentrequest',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.Cooperative'),
        ),
    ]
