# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20190308_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpaymenttransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='memberpaymenttransaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True),
        ),
    ]
