# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20190308_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpaymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK'), ('MOBILE MONEY', 'MOBILE MONEY')], max_length=16),
        ),
    ]
