# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20190308_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpaymentrequest',
            name='payment_method',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='bulkpaymentrequestlog',
            name='payment_method',
            field=models.CharField(max_length=18),
        ),
    ]
