# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_memberpaymenttransaction_farmer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpaymenttransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
