# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_memberpaymenttransaction_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoneyrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
