# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-21 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20230920_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneyrequest',
            name='response_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
