# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-11-19 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_mobilemoneyrequest_response_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpaymenttransaction',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
