# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-04-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
