# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-08 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_loanrequest_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
