# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-01-31 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_loanrequest_approved_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('INPROGRESS', 'INPROGRESS'), ('PAID', 'PAID'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=64),
        ),
    ]
