# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-13 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0006_auto_20250131_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('repayment_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_repayment',
            },
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanrepaymenttransaction',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.LoanRequest'),
        ),
    ]
