# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-14 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_auto_20250213_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='loan_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
