# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessages',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
