# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20240201_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessages',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
