# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
