# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('coop', '0006_auto_20190524_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='land_acreage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductVariation'),
        ),
    ]
