# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0007_auto_20200916_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
