# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-23 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0008_auto_20200923_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='is_refugee',
            field=models.BooleanField(default=False),
        ),
    ]
