# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-20 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coop', '0009_cooperativemember_is_refugee'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCooperativeAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'other_cooperative_admin',
            },
        ),
        migrations.AddField(
            model_name='cooperative',
            name='coop_abbreviation',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='payments_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='payments_authentication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='payments_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='sms_api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='sms_api_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='system_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='othercooperativeadmin',
            name='cooperative',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coop.Cooperative'),
        ),
        migrations.AddField(
            model_name='othercooperativeadmin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='othercooperativeadmin',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_cooperative_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
