# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-29 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0010_auto_20210220_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='app_id',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
