# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0012_auto_20210728_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='id_number',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
