# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-12 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0013_auto_20210728_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('contact_person_name', models.CharField(max_length=150)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.Cooperative')),
            ],
            options={
                'db_table': 'farmer_group',
            },
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='farmer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.FarmerGroup'),
        ),
    ]
