# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-01 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0014_auto_20211012_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.Cooperative'),
        ),
    ]
