# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-18 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0016_auto_20211117_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
