# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('coop', '0017_auto_20211118_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account'),
        ),
    ]
