# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-23 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211118_1455'),
        ('coop', '0018_cooperativemember_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account'),
        ),
    ]
