# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-03-07 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0019_cooperative_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='is_handicap',
            field=models.BooleanField(default=False),
        ),
    ]
