# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-03-21 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200924_0537'),
        ('coop', '0020_cooperativemember_is_handicap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('userprofile.profile',),
        ),
    ]
