# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-03-21 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0021_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='chia_trees',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
