# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-03-23 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0025_savings_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmergroup',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.Cooperative'),
        ),
    ]
