# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-03-23 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0027_auto_20230323_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperativemember',
            old_name='saving_balance',
            new_name='savings_balance',
        ),
        migrations.RenameField(
            model_name='farmergroup',
            old_name='saving_balance',
            new_name='savings_balance',
        ),
    ]
