# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-03-24 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0028_auto_20230323_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='has_mobile_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='own_phone',
            field=models.BooleanField(default=False),
        ),
    ]
