# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0030_auto_20230404_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='fpo_type',
            field=models.CharField(blank=True, choices=[('CP', 'Cooperative'), ('FG', 'Farmer Group'), ('AG', 'Aggreggator')], default='CP', max_length=150, null=True),
        ),
    ]
