# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-05 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0031_auto_20230404_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='chia_trees',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Shea Trees'),
        ),
    ]
