# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-18 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0032_auto_20230405_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Sex'),
        ),
    ]
