# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-18 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0033_auto_20230418_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='bee_hives',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Bee Hives'),
        ),
    ]
