# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0034_cooperativemember_bee_hives'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='farmer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.FarmerGroup'),
        ),
    ]
