# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-11-19 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0035_collection_farmer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberorder',
            name='status',
            field=models.CharField(choices=[('', '---------------------'), ('PENDING', 'PENDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('SHIP', 'SHIP'), ('DELIVERED', 'DELIVERED'), ('FAILED', 'FAILED'), ('ACCEPT_DELIVERY', 'ACCEPT_DELIVERY')], default='PENDING', max_length=255),
        ),
    ]
