# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-04-06 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0038_cooperativemember_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperativemember',
            old_name='chia_trees',
            new_name='shea_trees',
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='harvested_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='sunflower_acreage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='sunflower_collected',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='sunflower_planted',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32),
        ),
    ]
