# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-04-07 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0039_auto_20240407_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='harvested_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='sunflower_acreage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='sunflower_collected',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='sunflower_planted',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True),
        ),
    ]
