# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-04-11 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0042_harvesting_sunfloweracreage_sunflowercollection_sunflowerplantedquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvesting',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.Cooperative'),
        ),
    ]
