# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-04-11 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0045_registeredsimcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredsimcards',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
