# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-12 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coop', '0048_auto_20240508_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifying_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
