# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='descriprion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='topic',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
