# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_orderitem_unit_price'),
        ('activity', '0004_trainingsession_thematic_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='coop_member',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='coop_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.CooperativeMember'),
        ),
    ]
