# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_orderitem_unit_price'),
        ('activity', '0005_auto_20190220_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='coop_member',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='coop_member',
            field=models.ManyToManyField(to='coop.CooperativeMember'),
        ),
    ]
