# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20190223_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_trainer',
            },
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='external',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='external_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.ExternalTrainer'),
        ),
    ]
