# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20190322_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='external',
            new_name='is_external',
        ),
    ]
