# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-13 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_trainee_trainingphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingphotos',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
