# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_auto_20240228_2201'),
        ('activity', '0011_auto_20250213_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('agenda', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attendance', models.TextField()),
                ('attendance_sheet', models.FileField(upload_to=b'')),
                ('image', models.ImageField(upload_to=b'')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.District')),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
    ]
