# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-18 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20230418_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
