# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-05-15 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20230420_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
