# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_profile_date_recruited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.ManyToManyField(blank=True, to='conf.District'),
        ),
    ]
